# Generated by Django 4.2.11 on 2026-05-21 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('lightgbm', 'LightGBM'), ('lightgbm', 'LightGBM'), ('svm', 'Support Vector Machine'), ('lightgbm', 'LightGBM')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('staging', 'Staging'), ('deprecated', 'Deprecated')], default='staging', max_length=20)),
                ('model_type_label', models.CharField(default='Champion', max_length=20)),
                ('accuracy', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('roc_auc', models.FloatField(default=0.0)),
                ('training_samples', models.IntegerField(default=0)),
                ('feature_count', models.IntegerField(default=0)),
                ('training_duration_seconds', models.FloatField(default=0.0)),
                ('model_file_path', models.CharField(max_length=500)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('feature_importance', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_features', models.JSONField()),
                ('predicted_class', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('class_probabilities', models.JSONField()),
                ('shap_values', models.JSONField(default=dict)),
                ('processing_time_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_engine.mlmodel')),
            ],
        ),
    ]
