# Generated by Django 4.2.11 on 2026-05-21 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoHuntConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(default='default', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('schedule_cron', models.CharField(default='0 0 * * *', max_length=50)),
                ('target_models', models.JSONField(default=list)),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatScoringConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(default='default', max_length=50)),
                ('base_weight', models.FloatField(default=1.0)),
                ('ml_confidence_weight', models.FloatField(default=1.5)),
                ('historical_penalty', models.FloatField(default=0.8)),
                ('custom_rules', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
