# Generated by Django 4.2.11 on 2026-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0002_autohuntconfig_threatscoringconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='ab_test_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='champion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='traffic_split',
            field=models.FloatField(default=1.0),
        ),
    ]
