# Generated by Django 4.2.11 on 2026-09-02 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_id', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(choices=[('NPCI', 'NPCI'), ('BANK', 'Bank API'), ('I4C', 'I4C Push')], default='NPCI', max_length=20)),
                ('from_account', models.CharField(max_length=100)),
                ('from_bank_ifsc', models.CharField(max_length=20)),
                ('to_account', models.CharField(max_length=100)),
                ('to_bank_ifsc', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fraud_score', models.FloatField()),
                ('fraud_indicators', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ANALYZING', 'Analyzing'), ('FREEZE_REQUESTED', 'Freeze Requested'), ('ANALYZED', 'Analyzed'), ('FROZEN', 'Frozen'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='RECEIVED', max_length=30)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proactive_alerts', to='complaints.complaint')),
            ],
            options={
                'db_table': 'proactive_alerts',
                'ordering': ['-received_at'],
            },
        ),
    ]
