# Generated by Django 4.2.11 on 2026-09-02 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_account', models.CharField(max_length=100)),
                ('target_bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('target_bank_name', models.CharField(blank=True, max_length=100)),
                ('freeze_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('i4c_freeze_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FROZEN', 'Frozen'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('auto_triggered', models.BooleanField(default=False)),
                ('api_response_raw', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('cash_out_eta_minutes', models.IntegerField(default=15)),
                ('window_expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freeze_requests', to='complaints.complaint')),
                ('proactive_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freeze_requests', to='ingest.proactivealert')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freeze Request',
                'verbose_name_plural': 'Freeze Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
