# Generated by Django 4.2.11 on 2026-09-02 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuleNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_hash', models.CharField(help_text='SHA-256 hash of Account Number + IFSC', max_length=64, unique=True)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('node_type', models.CharField(choices=[('VICTIM', 'Victim Account'), ('LAYER_1', 'Layer 1 Mule Account'), ('LAYER_2', 'Layer 2 Mule Account'), ('LAYER_3', 'Layer 3 Mule Account'), ('UNKNOWN', 'Unknown Account')], default='UNKNOWN', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('freeze_status', models.CharField(choices=[('UNFROZEN', 'Unfrozen'), ('PENDING', 'Freeze Pending'), ('FROZEN', 'Frozen')], default='UNFROZEN', max_length=20)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('transaction_count', models.IntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('last_known_lat', models.FloatField(blank=True, null=True)),
                ('last_known_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuleEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_ref', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('hop_number', models.PositiveIntegerField()),
                ('linked_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_edges', to='complaints.complaint')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='graph.mulenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='graph.mulenode')),
            ],
            options={
                'unique_together': {('source_node', 'target_node', 'transaction_ref')},
            },
        ),
    ]
