import React, { useState, useEffect } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import apiClient from '../../utils/apiClient';
import toast from 'react-hot-toast';
import { Shield, CheckCircle, ArrowLeft, Loader2 } from 'lucide-react';

const MFASetupPage = ({ navigate }) => {
  const [setupData, setSetupData] = useState(null);
  const [totpCode, setTotpCode] = useState('');
  const [loading, setLoading] = useState(true);
  const [verifying, setVerifying] = useState(false);
  const [success, setSuccess] = useState(false);
  const [backupCodes, setBackupCodes] = useState([]);

  useEffect(() => {
    fetchMfaData();
  }, []);

  const fetchMfaData = async () => {
    try {
      setLoading(true);
      const response = await apiClient('/api/v1/auth/mfa/enable/', { method: 'POST' });
      const data = await response.json();
      setSetupData(data);
    } catch (err) {
      toast.error('Failed to initialize MFA setup');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async (e) => {
    e.preventDefault();
    if (totpCode.length !== 6) {
      toast.error('Code must be 6 digits');
      return;
    }
    
    try {
      setVerifying(true);
      const response = await apiClient('/api/v1/auth/mfa/verify/', { 
        method: 'POST', 
        body: JSON.stringify({ totp_code: totpCode }) 
      });
      if (!response.ok) throw new Error('Invalid code');
      const data = await response.json();
      setBackupCodes(data.backup_codes || []);
      setSuccess(true);
      toast.success('MFA enabled successfully!');
      // Wait for user to acknowledge backup codes instead of auto-redirecting
    } catch (err) {
      toast.error('Invalid code. Please try again.');
    } finally {
      setVerifying(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="w-8 h-8 text-emerald-500 animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div className="flex items-center gap-4 border-b border-emerald-900/30 pb-4">
        <button 
          onClick={() => navigate('profile')}
          className="p-2 hover:bg-emerald-900/20 text-emerald-500 rounded-lg transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div>
          <h1 className="text-2xl font-black text-white uppercase tracking-wider flex items-center gap-3">
            <Shield className="w-6 h-6 text-emerald-500" />
            Enable Two-Factor Authentication
          </h1>
          <p className="text-xs text-zinc-400 mt-1">
            Secure your account with a time-based one-time password (TOTP).
          </p>
        </div>
      </div>

      {!success ? (
        <div className="bg-black/40 border border-emerald-900/30 p-6 rounded-xl space-y-8">
          <div className="space-y-4">
            <h3 className="text-sm font-bold text-white uppercase">Step 1: Scan QR Code</h3>
            <p className="text-xs text-zinc-400">
              Open your authenticator app (e.g., Google Authenticator, Authy) and scan the QR code below.
            </p>
            <div className="flex justify-center p-6 bg-white rounded-lg w-max mx-auto">
              {setupData?.qr_code_url && (
                <QRCodeSVG value={setupData.qr_code_url} size={200} />
              )}
            </div>
            <div className="text-center">
              <p className="text-xs text-zinc-500">Or enter this setup key manually:</p>
              <code className="bg-zinc-900 px-3 py-1 rounded text-emerald-400 font-mono text-sm mt-2 inline-block">
                {setupData?.secret}
              </code>
            </div>
          </div>

          <div className="border-t border-emerald-900/30 pt-6 space-y-4">
            <h3 className="text-sm font-bold text-white uppercase">Step 2: Verify Setup</h3>
            <p className="text-xs text-zinc-400">
              Enter the 6-digit code generated by your app to verify the setup.
            </p>
            <form onSubmit={handleVerify} className="flex gap-4 max-w-sm mx-auto">
              <input
                type="text"
                maxLength="6"
                placeholder="000000"
                value={totpCode}
                onChange={(e) => setTotpCode(e.target.value.replace(/\D/g, ''))}
                className="flex-1 bg-black border border-emerald-900/50 rounded-lg px-4 text-center tracking-[0.5em] text-white font-mono placeholder:text-zinc-700 focus:outline-none focus:border-emerald-500"
                required
              />
              <button
                type="submit"
                disabled={verifying || totpCode.length !== 6}
                className="px-6 py-2 bg-emerald-600 hover:bg-emerald-500 text-black font-bold uppercase rounded-lg disabled:opacity-50 transition-colors flex items-center justify-center"
              >
                {verifying ? <Loader2 className="w-4 h-4 animate-spin" /> : 'Verify'}
              </button>
            </form>
          </div>
        </div>
      ) : (
        <div className="bg-black/40 border border-emerald-900/30 p-6 rounded-xl space-y-6">
          <div className="text-center space-y-4 pb-6 border-b border-emerald-900/30">
            <div className="w-16 h-16 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto">
              <CheckCircle className="w-8 h-8 text-emerald-500" />
            </div>
            <h2 className="text-xl font-bold text-white uppercase">MFA Enabled</h2>
            <p className="text-sm text-zinc-400">
              Your account is now protected by two-factor authentication.
            </p>
          </div>
          
          {backupCodes.length > 0 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-white uppercase">Backup Codes</h3>
                <button
                  onClick={() => {
                    const text = backupCodes.join('\\n');
                    const blob = new Blob([text], { type: 'text/plain' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = 'crimecast_backup_codes.txt';
                    a.click();
                  }}
                  className="px-3 py-1 bg-emerald-900/30 text-emerald-500 text-xs font-bold rounded uppercase hover:bg-emerald-900/50 transition-colors"
                >
                  Download .txt
                </button>
              </div>
              <div className="p-4 bg-zinc-950 border border-emerald-900/30 rounded-lg">
                <p className="text-xs text-rose-400 font-bold mb-4 uppercase">
                  WARNING: Save these codes now. They will not be shown again. Each code can only be used once.
                </p>
                <div className="grid grid-cols-2 gap-2 font-mono text-sm text-emerald-400">
                  {backupCodes.map((code, idx) => (
                    <div key={idx} className="bg-black py-1 px-3 rounded tracking-widest text-center">
                      {code}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          <div className="pt-4 flex justify-center">
            <button
              onClick={() => navigate('profile')}
              className="px-8 py-3 bg-emerald-600 hover:bg-emerald-500 text-black font-bold uppercase rounded-lg transition-colors"
            >
              Back to Profile
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default MFASetupPage;
