# Generated by Django 4.2.11 on 2026-08-22 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_organization_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('victim_name', models.CharField(max_length=255)),
                ('victim_phone', models.CharField(max_length=20)),
                ('victim_email', models.EmailField(blank=True, max_length=254)),
                ('victim_district', models.CharField(max_length=100)),
                ('victim_state', models.CharField(max_length=100)),
                ('victim_pincode', models.CharField(max_length=10)),
                ('fraud_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fraud_method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NET_BANKING', 'Net Banking'), ('PHONE_CALL', 'Phone Call'), ('EMAIL_PHISHING', 'Email Phishing'), ('OTHER', 'Other')], max_length=50)),
                ('fraud_timestamp', models.DateTimeField()),
                ('complaint_timestamp', models.DateTimeField(auto_now_add=True)),
                ('suspect_account_number', models.CharField(blank=True, max_length=100)),
                ('suspect_bank', models.CharField(blank=True, max_length=100)),
                ('suspect_phone', models.CharField(blank=True, max_length=20)),
                ('narrative_text', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_ANALYSIS', 'Under Analysis'), ('PREDICTION_ACTIVE', 'Prediction Active'), ('INTERCEPTED', 'Intercepted'), ('CLOSED', 'Closed'), ('FALSE_ALARM', 'False Alarm')], default='NEW', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='users.organization')),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_account', models.CharField(max_length=100)),
                ('from_bank', models.CharField(max_length=100)),
                ('from_ifsc', models.CharField(blank=True, max_length=20)),
                ('to_account', models.CharField(max_length=100)),
                ('to_bank', models.CharField(max_length=100)),
                ('to_ifsc', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('hop_number', models.PositiveIntegerField()),
                ('is_mule_flagged', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_hops', to='complaints.complaint')),
            ],
            options={
                'db_table': 'transaction_hops',
                'ordering': ['complaint', 'hop_number'],
            },
        ),
    ]
