# Generated by Django 4.2.11 on 2026-05-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('sla_breach', 'SLA Breach'), ('sla_warning', 'SLA Warning'), ('new_ioc', 'New IoC'), ('new_incident', 'New Incident'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
