# Generated by Django 4.2.11 on 2026-08-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('critical_threat', 'Critical Threat'), ('validation_request', 'Validation Request'), ('incident_assigned', 'Incident Assigned'), ('sandbox_complete', 'Sandbox Complete'), ('prediction_alert', 'Prediction Alert'), ('sla_warning', 'SLA Warning'), ('report_ready', 'Report Ready'), ('ml_drift', 'ML Drift Alert'), ('system_alert', 'System Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('critical_threat', 'Critical Threat'), ('validation_request', 'Validation Request'), ('incident_assigned', 'Incident Assigned'), ('sandbox_complete', 'Sandbox Complete'), ('prediction_alert', 'Prediction Alert'), ('sla_warning', 'SLA Warning'), ('report_ready', 'Report Ready'), ('ml_drift', 'ML Drift Alert'), ('system_alert', 'System Alert'), ('sla_breach', 'SLA Breach'), ('new_ioc', 'New IoC'), ('new_incident', 'New Incident'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'created_at'], name='core_notifi_user_id_dd1b42_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_sent', 'created_at'], name='core_notifi_email_s_57ee2c_idx'),
        ),
    ]
