# Generated by Django 4.2.11 on 2026-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_email_sent_notification_link_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow new users to register via the public signup endpoint.')),
                ('require_invitation', models.BooleanField(default=False, help_text='Require an admin invitation token to register.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Permission',
                'verbose_name_plural': 'Platform Permissions',
            },
        ),
    ]
