# Generated by Django 4.2.11 on 2026-08-07 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_users_role_a8f2ba_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('invite_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=10)),
                ('max_agents', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text='True if this user is the administrator of their organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('ioc_submission', 'IoC Submission'), ('threat_validation', 'Threat Validation'), ('evidence_anchor', 'Evidence Anchor'), ('role_grant', 'Role Grant'), ('report_export', 'Report Export'), ('api_key_created', 'API Key Created'), ('user_login', 'User Login'), ('config_change', 'Config Change'), ('false_positive', 'False Positive'), ('cert_mint', 'Certificate Mint'), ('sandbox_run', 'Sandbox Run'), ('packet_analysis', 'Packet Analysis'), ('gdpr_export', 'GDPR Data Export'), ('gdpr_delete', 'GDPR Account Deletion'), ('incident_created', 'Incident Created')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The company/tenant this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.organization'),
        ),
    ]
