# Generated by Django 4.2.11 on 2026-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_backup_codes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_a8f2ba_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_org_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
