# Generated by Django 4.2.11 on 2026-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_users_role_a8f2ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Operator', max_length=50),
        ),
    ]
