# Generated by Django 4.2.11 on 2026-08-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_initials',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
