# Generated by Django 4.2.11 on 2026-08-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar_initials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill_blockchain',
        ),
    ]
