# Generated by Django 4.2.11 on 2026-08-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
