# Generated by Django 4.2.11 on 2026-09-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_district'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='UserAchievement',
        ),
    ]
