[pytest]
DJANGO_SETTINGS_MODULE = tests.test_settings
python_files = test_*.py tests.py
python_classes = Test*
python_functions = test_*
addopts = 
    --tb=short
    --strict-markers
    -q
    -p no:cacheprovider
    -p no:pytest_ethereum
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests requiring external services
